/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package hr.algebra;

import hr.algebra.dal.MovieRepository;
import hr.algebra.dal.RepositoryFactory;
import hr.algebra.model.Actor;
import hr.algebra.model.Director;
import hr.algebra.model.Genre;
import hr.algebra.model.Movie;
import hr.algebra.utils.FileUtils;
import hr.algebra.utils.IconUtils;
import hr.algebra.utils.MessageUtils;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.text.JTextComponent;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.Optional;
import java.util.UUID;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author Next Design
 */
public class NewMovie extends javax.swing.JFrame {

    private MovieRepository repository;
    private final DefaultListModel<Actor> actorListModel = new DefaultListModel<>();
    private final DefaultListModel<Director> directorListModel = new DefaultListModel<>();
    private final DefaultListModel<Genre> genreListModel = new DefaultListModel<>();

    private final List<Director> directorsToDatabase = new ArrayList<>();
    private final List<Actor> actorsToDatabase = new ArrayList<>();
    private final List<Genre> genresToDatabase = new ArrayList<>();

    private List<JTextComponent> validationFields;
    private List<JLabel> errorLabels;

    private List<Director> allDirectors;
    private List<Actor> allActors;
    private List<Genre> allGenres;

    private Director existingDirector;
    private Actor existingActor;
    private Genre existingGenre;
    
    private static final String EXT = ".jpg";
    private static final String DIR = "src/assets";

    /**
     * Creates new form NewMovie
     */
    public NewMovie() {
        initComponents();
        setPanelIcon();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPoster = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblActorsError = new javax.swing.JLabel();
        cbActors = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstActors = new javax.swing.JList<>();
        btnActorsAdd = new javax.swing.JButton();
        btnRemoveActor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTitleError = new javax.swing.JLabel();
        txtTitle = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        lblDurationError = new javax.swing.JLabel();
        txtDuration = new javax.swing.JTextField();
        lblPubDateError = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        lblOriginalTitleError = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtOriginalTitle = new javax.swing.JTextField();
        txtPubDate = new javax.swing.JTextField();
        lblExpectedError = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtExpected = new javax.swing.JTextField();
        txtLink = new javax.swing.JTextField();
        lblLinkError = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lblDescriptionError = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        taDescription = new javax.swing.JTextArea();
        btnAddNewMovie = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        lblPosterError = new javax.swing.JLabel();
        txtPosterPath = new javax.swing.JTextField();
        btnAddPoster = new javax.swing.JButton();
        btnRefreshActors = new javax.swing.JButton();
        btnActorsDeleteFromList = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        lblActorsError1 = new javax.swing.JLabel();
        cbDirectors = new javax.swing.JComboBox<>();
        btnRefreshDirectors = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        lstDirectors = new javax.swing.JList<>();
        btnDirectorsAdd = new javax.swing.JButton();
        btnDirectorsDeleteFromList = new javax.swing.JButton();
        btnDirectorsAddNew = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblActorsError2 = new javax.swing.JLabel();
        cbGenres = new javax.swing.JComboBox<>();
        btnRefreshGenres = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        lstGenres = new javax.swing.JList<>();
        btnGenresAdd = new javax.swing.JButton();
        btnGenreDeleteFromList = new javax.swing.JButton();
        btnGenreAddNew = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add new movie");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        lblPoster.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPoster.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mov.png"))); // NOI18N
        lblPoster.setAlignmentY(0.0F);
        lblPoster.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(102, 102, 102), 1, true));
        lblPoster.setPreferredSize(new java.awt.Dimension(210, 400));
        lblPoster.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jLabel3.setText("Add actors");
        jLabel3.setToolTipText("");

        lblActorsError.setForeground(java.awt.Color.red);

        jScrollPane3.setViewportView(lstActors);

        btnActorsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnActorsAdd.setToolTipText("Add to list");
        btnActorsAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActorsAddActionPerformed(evt);
            }
        });

        btnRemoveActor.setText("Add new");
        btnRemoveActor.setToolTipText("Add new actor");
        btnRemoveActor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActorActionPerformed(evt);
            }
        });

        jLabel1.setText("Title");
        jLabel1.setToolTipText("");

        lblTitleError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblTitleError.setForeground(java.awt.Color.red);

        jLabel5.setText(" Duration (min)");
        jLabel5.setToolTipText("");

        lblDurationError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDurationError.setForeground(java.awt.Color.red);

        lblPubDateError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblPubDateError.setForeground(java.awt.Color.red);

        jLabel12.setText("Published date");
        jLabel12.setToolTipText("");

        lblOriginalTitleError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblOriginalTitleError.setForeground(java.awt.Color.red);

        jLabel2.setText("Original title");
        jLabel2.setToolTipText("");

        txtPubDate.setName("PubDate"); // NOI18N

        lblExpectedError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblExpectedError.setForeground(java.awt.Color.red);

        jLabel13.setText("Expected date");
        jLabel13.setToolTipText("");

        txtExpected.setName("ExpDate"); // NOI18N

        lblLinkError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblLinkError.setForeground(java.awt.Color.red);

        jLabel7.setText("Link");
        jLabel7.setToolTipText("");

        lblDescriptionError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblDescriptionError.setForeground(java.awt.Color.red);

        jLabel6.setText("Description");

        taDescription.setColumns(20);
        taDescription.setLineWrap(true);
        taDescription.setRows(5);
        jScrollPane2.setViewportView(taDescription);

        btnAddNewMovie.setText("Add movie");
        btnAddNewMovie.setToolTipText("Save new movie to a database");
        btnAddNewMovie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewMovieActionPerformed(evt);
            }
        });

        btnCancel.setText("Cancel");
        btnCancel.setToolTipText("Cancel creating new movie");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel8.setText("Poster");
        jLabel8.setToolTipText("");

        lblPosterError.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        lblPosterError.setForeground(java.awt.Color.red);

        btnAddPoster.setText("Add poster");
        btnAddPoster.setToolTipText("Add poster for the movie");
        btnAddPoster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPosterActionPerformed(evt);
            }
        });

        btnRefreshActors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnRefreshActors.setToolTipText("Refresh actors");
        btnRefreshActors.setBorder(null);
        btnRefreshActors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActorsActionPerformed(evt);
            }
        });

        btnActorsDeleteFromList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnActorsDeleteFromList.setToolTipText("Remove from list");
        btnActorsDeleteFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActorsDeleteFromListActionPerformed(evt);
            }
        });

        jLabel4.setText("Add directors");
        jLabel4.setToolTipText("");

        lblActorsError1.setForeground(java.awt.Color.red);

        btnRefreshDirectors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnRefreshDirectors.setToolTipText("Refresh directors");
        btnRefreshDirectors.setBorder(null);
        btnRefreshDirectors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshDirectorsActionPerformed(evt);
            }
        });

        jScrollPane4.setViewportView(lstDirectors);

        btnDirectorsAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnDirectorsAdd.setToolTipText("Add to list");
        btnDirectorsAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorsAddActionPerformed(evt);
            }
        });

        btnDirectorsDeleteFromList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDirectorsDeleteFromList.setToolTipText("Remove from list");
        btnDirectorsDeleteFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorsDeleteFromListActionPerformed(evt);
            }
        });

        btnDirectorsAddNew.setText("Add new");
        btnDirectorsAddNew.setToolTipText("Add new director");
        btnDirectorsAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDirectorsAddNewActionPerformed(evt);
            }
        });

        jLabel9.setText("Add genre");
        jLabel9.setToolTipText("");

        lblActorsError2.setForeground(java.awt.Color.red);

        btnRefreshGenres.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/refresh.png"))); // NOI18N
        btnRefreshGenres.setToolTipText("Refresh genres");
        btnRefreshGenres.setBorder(null);
        btnRefreshGenres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshGenresActionPerformed(evt);
            }
        });

        jScrollPane5.setViewportView(lstGenres);

        btnGenresAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnGenresAdd.setToolTipText("Add to list");
        btnGenresAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenresAddActionPerformed(evt);
            }
        });

        btnGenreDeleteFromList.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnGenreDeleteFromList.setToolTipText("Remove from list");
        btnGenreDeleteFromList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreDeleteFromListActionPerformed(evt);
            }
        });

        btnGenreAddNew.setText("Add new");
        btnGenreAddNew.setToolTipText("Add new genre");
        btnGenreAddNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenreAddNewActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(93, 93, 93)
                        .addComponent(btnAddPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblPosterError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtPosterPath, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblDurationError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 634, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblDescriptionError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
                                .addComponent(txtOriginalTitle)
                                .addComponent(txtLink)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblLinkError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblOriginalTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblPubDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel13)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblExpectedError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(txtPubDate, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE)
                                .addComponent(txtExpected)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbActors, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRefreshActors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(btnActorsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnActorsDeleteFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(btnRemoveActor, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblActorsError, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbDirectors, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRefreshDirectors, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnDirectorsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnDirectorsDeleteFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDirectorsAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblActorsError1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cbGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnRefreshGenres, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(btnGenresAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnGenreDeleteFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnGenreAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(lblActorsError2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(20, 20, 20))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnAddNewMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(303, 303, 303))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 386, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(lblActorsError1, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnRefreshDirectors, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbDirectors, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnDirectorsDeleteFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnDirectorsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnDirectorsAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel3)
                                            .addComponent(lblActorsError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnRefreshActors, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbActors, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnActorsDeleteFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnActorsAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnRemoveActor, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel9)
                                            .addComponent(lblActorsError2, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(btnRefreshGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(cbGenres, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(12, 12, 12)
                                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(btnGenreDeleteFromList, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                .addComponent(btnGenresAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(btnGenreAddNew, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addGap(108, 108, 108)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel2)
                                            .addComponent(lblOriginalTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtOriginalTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel12)
                                            .addComponent(lblPubDateError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtPubDate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblLinkError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(lblPosterError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtPosterPath, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtExpected, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel5)
                                    .addComponent(lblDurationError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtDuration, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel1)
                                    .addComponent(lblTitleError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(94, 94, 94)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(lblExpectedError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(lblDescriptionError, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnAddPoster, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAddNewMovie, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPosterActionPerformed
        File file = FileUtils.uploadFile("Images", "jpg", "jpeg", "png");
        if (file == null) {
            return;
        }
        txtPosterPath.setText(file.getAbsolutePath());
        setIcon(lblPoster, file);
    }//GEN-LAST:event_btnAddPosterActionPerformed

    private void btnAddNewMovieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewMovieActionPerformed
        if (formValid()) {
            Movie m = new Movie();
            m.setTitle(txtTitle.getText().trim());
            m.setPubDate(LocalDateTime.parse(txtPubDate.getText().trim(), Movie.DATE_FORMATTER));
            m.setDescription(taDescription.getText().trim());
            m.setOriginalTitle(txtOriginalTitle.getText().trim());
            m.setDuration(txtDuration.getText().trim());
            
            try {
                m.setPosterPath(copyImageToAssets(m, txtPosterPath.getText().trim()));
            } catch (IOException ex) {
                Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            m.setLink(txtLink.getText().trim());
            m.setExpected(LocalDate.parse(txtExpected.getText().trim(), Movie.DATE_FORMAT));
            try {
                int idMovie = repository.createMovie(m);

                for (Director director : directorsToDatabase) {
                    Optional<Director> d = repository.selectDirectorByName(director);
                    if (d.isPresent()) {
                        existingDirector = d.get();
                        repository.populateMovieDirection(idMovie, existingDirector.getIdDirector());
                    } else {
                        repository.createDirector(idMovie, director);
                    }
                }

                for (Actor actor : actorsToDatabase) {
                    Optional<Actor> a = repository.selectActorByName(actor);
                    if (a.isPresent()) {
                        existingActor = a.get();
                        repository.populateMovieActor(idMovie, existingActor.getIdActor());
                    } else {
                        repository.createActor(idMovie, actor);
                    }
                }

                for (Genre genre : genresToDatabase) {
                    Optional<Genre> g = repository.selectGenreByName(genre);
                    if (g.isPresent()) {
                        existingGenre = g.get();
                        repository.populateMovieGenre(idMovie, existingGenre.getIdGenre());
                    } else {
                        repository.createGenre(idMovie, genre);
                    }
                }

                dispose();

            } catch (Exception ex) {
                Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
            }
        }


    }//GEN-LAST:event_btnAddNewMovieActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        int dialogResult = MessageUtils.showConfirmDialog("Cancel", "Are you sure?");
        if (dialogResult == JOptionPane.YES_OPTION) {
            dispose();
        }
    }//GEN-LAST:event_btnCancelActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        init();
    }//GEN-LAST:event_formComponentShown

    private void btnDirectorsAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorsAddActionPerformed
        Director d = (Director) cbDirectors.getSelectedItem();
        directorListModel.addElement(d);
        directorsToDatabase.add(d);
        lstDirectors.setModel(directorListModel);
    }//GEN-LAST:event_btnDirectorsAddActionPerformed

    private void btnActorsAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActorsAddActionPerformed
        Actor a = (Actor) cbActors.getSelectedItem();
        actorListModel.addElement(a);
        actorsToDatabase.add(a);
        lstActors.setModel(actorListModel);
    }//GEN-LAST:event_btnActorsAddActionPerformed

    private void btnActorsDeleteFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActorsDeleteFromListActionPerformed
        Actor a = lstActors.getSelectedValue();
        if (a != null) {
            actorListModel.removeElement(a);
            lstActors.setModel(actorListModel);
        }
    }//GEN-LAST:event_btnActorsDeleteFromListActionPerformed

    private void btnDirectorsDeleteFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorsDeleteFromListActionPerformed
        Director d = lstDirectors.getSelectedValue();
        if (d != null) {
            directorListModel.removeElement(d);
            lstDirectors.setModel(directorListModel);
        }
    }//GEN-LAST:event_btnDirectorsDeleteFromListActionPerformed

    private void btnGenresAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenresAddActionPerformed
        Genre g = (Genre) cbGenres.getSelectedItem();
        genreListModel.addElement(g);
        genresToDatabase.add(g);
        lstGenres.setModel(genreListModel);
    }//GEN-LAST:event_btnGenresAddActionPerformed

    private void btnGenreDeleteFromListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreDeleteFromListActionPerformed
        Genre g = lstGenres.getSelectedValue();
        if (g != null) {
            genreListModel.removeElement(g);
            lstGenres.setModel(genreListModel);
        }
    }//GEN-LAST:event_btnGenreDeleteFromListActionPerformed

    private void btnRefreshActorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActorsActionPerformed
        try {
            initActors();
        } catch (Exception ex) {
            Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshActorsActionPerformed

    private void btnRefreshDirectorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshDirectorsActionPerformed
        try {
            initDirectors();
        } catch (Exception ex) {
            Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshDirectorsActionPerformed

    private void btnRefreshGenresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshGenresActionPerformed
        try {
            initGenres();
        } catch (Exception ex) {
            Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnRefreshGenresActionPerformed

    private void btnRemoveActorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActorActionPerformed
        //AddNewActor newActor = new AddNewActor();
        //newActor.setVisible(true);
        new AddNewActor((JFrame) SwingUtilities.windowForComponent(this), true).setVisible(true);
    }//GEN-LAST:event_btnRemoveActorActionPerformed

    private void btnDirectorsAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDirectorsAddNewActionPerformed
        //AddNewDirector newDirector = new AddNewDirector();
        //newDirector.setVisible(true);
        new AddNewDirector((JFrame) SwingUtilities.windowForComponent(this), true).setVisible(true);
    }//GEN-LAST:event_btnDirectorsAddNewActionPerformed

    private void btnGenreAddNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenreAddNewActionPerformed
        //AddNewGenre newGenre = new AddNewGenre();
        //newGenre.setVisible(true);
        new AddNewGenre((JFrame) SwingUtilities.windowForComponent(this), true).setVisible(true);
    }//GEN-LAST:event_btnGenreAddNewActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewMovie.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewMovie().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActorsAdd;
    private javax.swing.JButton btnActorsDeleteFromList;
    private javax.swing.JButton btnAddNewMovie;
    private javax.swing.JButton btnAddPoster;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDirectorsAdd;
    private javax.swing.JButton btnDirectorsAddNew;
    private javax.swing.JButton btnDirectorsDeleteFromList;
    private javax.swing.JButton btnGenreAddNew;
    private javax.swing.JButton btnGenreDeleteFromList;
    private javax.swing.JButton btnGenresAdd;
    private javax.swing.JButton btnRefreshActors;
    private javax.swing.JButton btnRefreshDirectors;
    private javax.swing.JButton btnRefreshGenres;
    private javax.swing.JButton btnRemoveActor;
    private javax.swing.JComboBox<Actor> cbActors;
    private javax.swing.JComboBox<Director> cbDirectors;
    private javax.swing.JComboBox<Genre> cbGenres;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblActorsError;
    private javax.swing.JLabel lblActorsError1;
    private javax.swing.JLabel lblActorsError2;
    private javax.swing.JLabel lblDescriptionError;
    private javax.swing.JLabel lblDurationError;
    private javax.swing.JLabel lblExpectedError;
    private javax.swing.JLabel lblLinkError;
    private javax.swing.JLabel lblOriginalTitleError;
    private javax.swing.JLabel lblPoster;
    private javax.swing.JLabel lblPosterError;
    private javax.swing.JLabel lblPubDateError;
    private javax.swing.JLabel lblTitleError;
    private javax.swing.JList<Actor> lstActors;
    private javax.swing.JList<Director> lstDirectors;
    private javax.swing.JList<Genre> lstGenres;
    private javax.swing.JTextArea taDescription;
    private javax.swing.JTextField txtDuration;
    private javax.swing.JTextField txtExpected;
    private javax.swing.JTextField txtLink;
    private javax.swing.JTextField txtOriginalTitle;
    private javax.swing.JTextField txtPosterPath;
    private javax.swing.JTextField txtPubDate;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables

    private void setPanelIcon() {
        this.setIconImage(new ImageIcon(getClass().getResource("/images/camera.png")).getImage());
    }

    private void init() {
        try {
            initRepository();
            initValidation();
            initActors();
            initDirectors();
            initGenres();
        } catch (Exception ex) {
            Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    private void initRepository() throws Exception {
        repository = RepositoryFactory.getRepository();
    }

    private void initActors() throws Exception {
        allActors = repository.getAllActors();
        for (Actor actor : allActors) {
            cbActors.addItem(new Actor(actor.getIdActor(), actor.getActorName()));
        }
    }

    private void initDirectors() throws Exception {
        allDirectors = repository.getAllDirectors();
        for (Director d : allDirectors) {
            cbDirectors.addItem(new Director(d.getIdDirector(), d.getDirectorName()));
        }
    }

    private void initGenres() throws Exception {
        allGenres = repository.getAllGenres();
        for (Genre g : allGenres) {
            cbGenres.addItem(new Genre(g.getIdGenre(), g.getGenreName()));
        }
    }

    private void setIcon(JLabel lblPoster, File file) {
        try {
            lblPoster.setIcon(IconUtils.createIcon(file, lblPoster.getWidth(), lblPoster.getHeight()));
        } catch (IOException ex) {
            Logger.getLogger(NewMovie.class.getName()).log(Level.SEVERE, null, ex);
            MessageUtils.showErrorMessage("Error", "Unable to set icon!");
        }
    }

    private void initValidation() {
        validationFields = Arrays.asList(txtTitle, txtOriginalTitle, txtLink, txtDuration, txtPubDate, txtExpected, txtPosterPath, taDescription);
        errorLabels = Arrays.asList(lblTitleError, lblOriginalTitleError, lblLinkError, lblDurationError, lblPubDateError, lblExpectedError, lblPosterError, lblDescriptionError);
    }

    private boolean formValid() {
        boolean ok = true;
        for (int i = 0; i < validationFields.size(); i++) {
            ok &= !validationFields.get(i).getText().trim().isEmpty();
            errorLabels.get(i).setText(validationFields.get(i).getText().trim().isEmpty() ? "*" : "");

            if ("PubDate".equals(validationFields.get(i).getName())) {
                try {
                    LocalDateTime.parse(validationFields.get(i).getText().trim(), Movie.DATE_FORMATTER);
                    errorLabels.get(i).setText("");
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setText("*");
                }
            }

            if ("ExpDate".equals(validationFields.get(i).getName())) {
                try {
                    LocalDate.parse(validationFields.get(i).getText().trim(), Movie.DATE_FORMAT);
                    errorLabels.get(i).setText("");
                } catch (Exception e) {
                    ok = false;
                    errorLabels.get(i).setText("*");
                }
            }
        }
        return ok;
    }

    private String copyImageToAssets(Movie m, String pictureUrl) throws IOException {
        String ext = pictureUrl.substring(pictureUrl.lastIndexOf("."));
            if (ext.length() > 4) {
                ext = EXT;
            }
            String pictureName = UUID.randomUUID() + ext;
            String localPicturePath = DIR + File.separator + pictureName;

            FileUtils.copy(pictureUrl, localPicturePath);
            m.setPosterPath(localPicturePath);
             return localPicturePath;
    }

    
}
